# -*- coding: utf-8 -*-
"""Grupo 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTQTUxUejcaAIWxShXF-vQOcXn38HEB0

## **CASO 2: Pacientes de una clínica – GRUPO2**
Una clínica almacena información de pacientes en un archivo pacientes.json, pero presenta inconsistencias por ingreso manual.

Preparar datos para análisis epidemiológico.

# **Tareas**

*   Normalizar nombres (mayúsculas)
*   Validar rango de edad
*   Limpiar duplicados por DNI
*   Estandarizar sexo
*   Completar o eliminar datos faltantes
"""

#Importamos la libreria pandas
import pandas as pd

#Extraccion y Transformacion del archivo pacientes.json
df = pd.read_json('pacientes.json')



#Normalizar nombres (Mayúsculas)
df['nombre'] = df['nombre'].str.upper()

#Validar rango de edad
df = df[df['edad'] >= 0]
df = df[df['edad'] <= 120]

#Eliminar duplicados por DNI
df = df.drop_duplicates(subset=['dni'])

#Estandarizar el sexo
df['sexo'] = df['sexo'].str.upper()
df['sexo'] = df['sexo'].replace('MASCULINO', 'M')
df['sexo'] = df['sexo'].str.replace('MALE', 'M')
df['sexo'] = df['sexo'].replace('FEMENINO', 'F')

#Completar o eliminar datos faltantes
df['telefono'] = df['telefono'].fillna('Sin telefono')
df['diagnostico'] = df['diagnostico'].fillna('Sin diagnostico')

#Eliminar errores finales
df_ant = df.copy()
df = df.dropna()

#Ver el resultado final en formato tabla de Pandas
print(df)

#Carga a un archivo JSON pacientes.json
df.to_json("pacientes_limpias.json", orient="records", indent=4)