# -*- coding: utf-8 -*-
"""EC1-GRUPO 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135Zrskzgz-0sCzzJwmxfejKoyWXW2RlL

## **CASO 2: ALQUILER DE VEHICULOS – GRUPO 2**

Desarrollar un ETL, el cual debe contemplar lo siguiente:


1. Extraccion de los datos

2. Perfilado de los datos (identificar datos nulos, duplicados, detalle de los datos, etc.)

3. Limpieza de los datos (nulos, valores invalidos, duplicados, etc.)

4. Transformación de los datos (fechas, textos, tipos de datos, variables nuevas, etc.)

5. Validacion de los datos (reglas de negocio, rangos, consistencia, etc.)

6. Carga (generar un archivo .csv limpio)

## **1. Extracción de los datos**
En esta etapa cargamos los datos desde la fuente (archivo CSV) hacia un DataFrame de Pandas.
"""

#Importamos la libreria pandas
import pandas as pd

#Extraccion y Transformacion del archivo alquiler_vehiculos_sucio.csv
df = pd.read_csv('alquiler_vehiculos_sucio.csv')

#Verificamos que los datos se hallan extraido correctamente
print(df)

"""## **2. Perfilado de los datos**
Analizamos la calidad de los datos para identificar nulos, duplicados y visualizar el estado actual.

"""

print("\n--- Cantidad de Valores Nulos ---")
print(df.isnull().sum())

print("\n--- Cantidad de Filas Duplicadas ---")
print(df.duplicated().sum())

print("\n--- Estadísticas Descriptivas ---")
display(df.describe(include='all'))

"""## **3. Limpieza de los datos**
Procedemos a la limpieza de los datos (nulos, valores invalidos, duplicados, etc.)
"""

#Eliminar duplicados exactos
df_clean = df.drop_duplicates().copy()

#Completar datos faltantes en columnas de texto
df_clean['vehiculo'] = df_clean['vehiculo'].fillna('Desconocidoo')
df_clean['marca'] = df_clean['marca'].fillna('Desconocido')
df_clean['tipo_vehiculo'] = df_clean['tipo_vehiculo'].fillna('Desconocido')
df_clean['ciudad'] = df_clean['ciudad'].fillna('Desconocido')
df_clean['accidente'] = df_clean['accidente'].fillna('Desconocido')

#Completar datos faltantes en columnas de numéricas
df_clean['monto_alquiler'] = df_clean['monto_alquiler'].fillna(0)
df_clean['kilometros'] = df_clean['kilometros'].fillna(0)

"""## **4. Transformación de los datos**
Homologamos el texto (mayúsculas/minúsculas), corregimos valores inconsistentes en la columna accidente y creamos una nueva variable calculada.
"""

#Estandarización de textos a formato Title o Upper y eliminación de espacios extra
df_clean['vehiculo'] = df_clean['vehiculo'].str.upper().str.strip()
df_clean['marca'] = df_clean['marca'].str.title().str.strip()
df_clean['tipo_vehiculo'] = df_clean['tipo_vehiculo'].str.title().str.strip()
df_clean['ciudad'] = df_clean['ciudad'].str.title().str.strip()

#Estandarización de la columna 'accidente' (SI / NO)
df_clean['accidente'] = df_clean['accidente'].str.strip().str.upper()
df_clean['accidente'] = df_clean['accidente'].replace({'SÍ': 'SI', 'SÌ': 'SI', 'DESCONOCIDO': 'NO'})

#Creación de nueva variable: costo total = alquiler + mantenimiento
df_clean['costo_total'] = df_clean['monto_alquiler'] + df_clean['mantenimiento']

"""## 5. **Validación de los datos**
Aplicamos reglas de negocio para asegurar que no se filtren datos atípicos o sin sentido lógico.
"""

#Regla 1: Días de alquiler estrictamente positivos
regla_1 = df_clean['dias_alquiler'] > 0

#Regla 2: Montos no pueden ser negativos
regla_2 = (df_clean['monto_alquiler'] >= 0) & (df_clean['mantenimiento'] >= 0)

#Regla 3: Año del vehículo razonable (posterior a 1990)
regla_3 = (df_clean['anio_vehiculo'] > 1990) & (df_clean['anio_vehiculo'] <= 2027)

df_validado = df_clean[regla_1 & regla_2 & regla_3].copy()

"""## **6. Carga**
Guardamos los datos ya procesados y listos en un nuevo archivo CSV.
"""

#Carga a un archivo CSV alquiler_vehiculos_sucio.csv
df_validado.to_csv("alquiler_vehiculos_datalimpia.csv", index=False, encoding='utf-8')